workflows:
  zambia-real-estate-apk:
    name: Zambia Real Estate APK
    environment:
      flutter: stable
      vars:
        FLUTTER_VERSION: 1.0.0
    scripts:
      - name: Clean build
        script: flutter clean
      - name: Get packages
        script: flutter pub get
      - name: Build APK
        script: flutter build apk --release
    artifacts:
      - build/app/outputs/flutter-apk/app-release.apk
    publishing:
      email:
        recipients:
          - your-email@gmail.com