name: zambia_real_estate
description: A real estate app for Zambia - find properties, connect with agents
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # UI & Icons
  cupertino_icons: ^1.0.6
  google_fonts: ^6.1.0
  
  # Image picking
  image_picker: ^1.0.4

  file_picker: ^8.1.4 
  
  #supabase
  supabase_flutter: ^2.0.0
  
  # Local storage
  shared_preferences: ^2.2.2
  
  # Navigation
  go_router: ^12.0.0
  
  # WhatsApp integration
  url_launcher: ^6.2.1
  
  # Form validation
  flutter_form_builder: ^9.1.0
  
  # Loading states
  shimmer: ^3.0.0
  
  # Date formatting
  intl: ^0.18.0
  
  # Image caching
  cached_network_image: ^3.3.0
  
  # Offline & Caching
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  path_provider: ^2.1.1
  connectivity_plus: ^5.0.2


  # Video Player
  video_player: ^2.8.6
  chewie: ^1.7.5  # Video controls with better UI
  
  # Video thumbnails
  #video_thumbnail: ^0.5.3

  
  # Image compression
  flutter_image_compress: ^2.4.0

  firebase_messaging: ^15.0.0
  flutter_local_notifications: ^16.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  hive_generator: ^2.0.0
  build_runner: ^2.4.6

flutter:
  uses-material-design: true
